FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y upgrade && \
    apt-get -y install python3.8 && \
    apt update && apt install python3-pip -y

ENV XL_IDP_PATH_DOCKER=${XL_IDP_PATH_DOCKER}

# Install Cron
RUN apt-get update && apt-get -y install cron

RUN chmod -R 777 ${XL_IDP_PATH_DOCKER}

COPY requirements.txt ./

RUN pip install -r requirements.txt

WORKDIR ${XL_IDP_PATH_DOCKER}

COPY crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab

CMD ["/bin/sh", "-c", "printenv > /etc/environment && cron -f"]